### ISSUE TITLE
checklist of change to look in the building system 

### ISSUE THREAD

**Issue by massich** [openmeeg/openmeeg#257]
This issue is a list of things to review regarding the building system. At some point. It's main purpose is gathering potential problems or improvements to motivate a discussion or roadmap

- [ ] Use `GIT_SHALLOW 1` to safe download bandwidth
- [ ] `BUILD_SHARED_LIBS` seems to not work for **mkl**
https://github.com/openmeeg/openmeeg/blob/c7d5d7481594c6f6d80c6803112bdf09c6b92d1f/OpenMEEG/cmake/FindMKL.cmake#L139
- [ ] unnecessary conditional. There's no need to check the conditional if the same variable is assigned
https://github.com/openmeeg/openmeeg/blob/c7d5d7481594c6f6d80c6803112bdf09c6b92d1f/build_tools/travis/install.sh#L8-L15

**Comment by papadop** [comment]
Why do you say that BUILD_SHARED_LIBS is not working with MKL ?? It works well on fedora and ubuntu (actually for ubuntu we need shared libs otherwise one test fails). For MacOS, indeed the BUILD_SHARED_LIBS does not work and I do not remember exactly why (but we tested it. @agramfort do you remember ?).

I'll try the GIT_SHALLOW parameter...

**Comment by massich** [comment]
Wait I just opened the issue to keep track of all the things I find within the cmakes.

**Comment by massich** [comment]
Do not adress any of those points

**Comment by massich** [comment]
Maybe this building system can be used as example https://github.com/cginternals/cpplocate
