### ISSUE TITLE
ENH: Plan for Windows, conda-forge, and PyPI wheels

### ISSUE THREAD

**Issue by larsoner** [openmeeg/openmeeg#449]
## ☑ Phase 1: Windows CIs and OpenBLAS

Get up-to-date packages on conda-forge for Linux and macOS:

- [x] Merge [this](https://github.com/openmeeg/openmeeg/pull/443)
- [x] Cut 2.4.2 release: https://github.com/openmeeg/openmeeg/releases/tag/2.4.2
- [x] Use this release in https://github.com/conda-forge/openmeeg-feedstock/pull/18 and merge if it's green
- [x] Add arm64 support: https://github.com/conda-forge/openmeeg-feedstock/pull/19

## ☑ Phase 2: MKL, MSVC support, and Windows conda-forge

Get Windows working (again?) on conda-forge:

- [x] Reenable Windows on CI here by following SciPy's OpenBLAS build instructions: https://github.com/openmeeg/openmeeg/pull/447
- [x] Fix MKL on CIs using conda-forge for simplicity: https://github.com/openmeeg/openmeeg/pull/455
- [x] Use OpenBLAS static builds on conda-forge: https://github.com/conda-forge/openmeeg-feedstock/pull/23
- [x] Fix MSVC support for OpenMEEG code: #457
- [x] Cut 2.4.3: https://github.com/openmeeg/openmeeg/releases/tag/2.4.3
- [x] Fix MSVC support for OpenBLAS: #454
- [x] Fix installation using `cmake --target install` or whatever conda-forge currently uses (ensure it works for the python libraries): https://github.com/openmeeg/openmeeg/pull/461
- [x] Cut 2.4.4: https://github.com/openmeeg/openmeeg/releases/tag/2.4.4
- [x] Reenable Windows on conda-forge: https://github.com/conda-forge/openmeeg-feedstock/pull/24

## ☑ Phase 3: PyPI wheels

Get PyPI wheels working by following whatever NumPy/SciPy does to release wheels with OpenBLAS. Something like the following is probably cleanest:

- [x] Adjust cmake scripts to create a more standard folder structure like:
  - `wrapping/python/openmeeg/__init__.py`
  - `wrapping/python/openmeeg/tests/*.py`
  https://github.com/openmeeg/openmeeg/pull/451
- [x] Add `wrapping/python/setup.py` that assumes SWIG has already been run: https://github.com/openmeeg/openmeeg/pull/453
- [x] Allow SWIG to be used separately from cmake and use `setup.py` to build extensions properly: https://github.com/openmeeg/openmeeg/pull/465
- [x] Create wheels on Linux using cibuildwheel: https://github.com/openmeeg/openmeeg/pull/466
- [x] Reenable coverage: https://github.com/openmeeg/openmeeg/pull/470
- [x] Get TestPyPI wheels to upload properly on `main` (work on cibuildwheel deploy step)
- [x] Create wheels on macOS Intel using cibuildwheel: https://github.com/openmeeg/openmeeg/pull/468
- [x] Switch most `build_and_test.yml` jobs to use MSVC instead of mingw64: https://github.com/openmeeg/openmeeg/pull/473
- [x] Create wheels on macOS arm64: https://github.com/openmeeg/openmeeg/pull/471
- [x] Bisect `DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM=...`:
   - [x] `10.0.14393.0`: good
   - [x] `10.0.15063.0`: good
   - [x] `10.0.16299.0`: good
   - [x] `10.0.17763.0`: bad
- [x] Factor out Python tests to just run using `pytest` and run them in cibuildwheel: https://github.com/openmeeg/openmeeg/pull/474
- [x] Add `build_and_test.yml` job that uses OpenBLAS 0.3.20: https://github.com/openmeeg/openmeeg/pull/475
- [x] Add PyPy build and ability to skip `test_mesh_full.py` test: https://github.com/openmeeg/openmeeg/pull/475
- [x] Use `oldest-supported-numpy` on most builds and NumPy `--pre` builds: https://github.com/openmeeg/openmeeg/pull/475
- [x] Create wheels on Windows: https://github.com/openmeeg/openmeeg/pull/472
- [x] Reenable PyPy wheels and use `oldest-supported-numpy`: https://github.com/openmeeg/openmeeg/pull/477
- [x] Update README to mention pip-installability (and badge for cibuildwheel job): https://github.com/openmeeg/openmeeg/pull/477
- [x] Check that wheels uploaded to TestPyPI actually work on all four OS/arch combos
  - [x] macOS M1
  - [x] macOS Intel
  - [x] Windows
  - [x] Linux
- [x] Release 2.4.5: https://github.com/openmeeg/openmeeg/releases/tag/2.4.5
- [x] Add `release` trigger for `cibuildwheel`: https://github.com/openmeeg/openmeeg/pull/479
- [x] Release 2.4.6: https://github.com/openmeeg/openmeeg/releases/tag/2.4.6
- [x] Check that wheels uploaded to PyPI actually work on all four OS/arch combos
  - [x] macOS M1
  - [x] macOS Intel
  - [x] Windows
  - [x] Linux
- [x] Update `openmeeg-feedstock` to run tests: https://github.com/conda-forge/openmeeg-feedstock/pull/26
- [x] Bump to 2.4.6.dev0: https://github.com/openmeeg/openmeeg/pull/480

## ☐ Phase 4: Fix actual code

- [x] Fix protection against zero for Fedora folks: https://github.com/openmeeg/openmeeg/pull/482
- [x] Release 2.4.7: https://github.com/openmeeg/openmeeg/releases/tag/2.4.7
- [x] Restore commits reverted in #457: @papadop in #498, #501, #502 and #503.

_Originally posted by @larsoner in https://github.com/openmeeg/openmeeg/issues/443#issuecomment-1159691192_

**Comment by larsoner** [comment]
Now that we have Windows + PyPI wheels, I'm going to close this and make separate issues out of the remaining TODOs
